version: '3.8'  # Specify a compatible Docker Compose version

services:
  mongo:
    image: mongo:5.0  # Use MongoDB version 5.0 (adjust as needed)
    container_name: mongodb-dev  # Optional container name
    restart: always  # Restart the container if it fails
    ports:
      - 27017:27017  # Map MongoDB's port 27017 to the host machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: password  # Set the root password (replace with a secure one)
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data using a volume

volumes:
  mongo-data:  # Define the volume for MongoDB data
