/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ShortenImport } from "./routes/shorten";
import { Route as PricingImport } from "./routes/pricing";
import { Route as IntegrationImport } from "./routes/integration";
import { Route as GenerateImport } from "./routes/generate";
import { Route as FaqsImport } from "./routes/faqs";
import { Route as ContactImport } from "./routes/contact";
import { Route as AuthImport } from "./routes/auth";
import { Route as IndexImport } from "./routes/index";

// Create Virtual Routes

const AboutLazyImport = createFileRoute("/about")();

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
	path: "/about",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/about.lazy").then((d) => d.Route));

const ShortenRoute = ShortenImport.update({
	path: "/shorten",
	getParentRoute: () => rootRoute,
} as any);

const PricingRoute = PricingImport.update({
	path: "/pricing",
	getParentRoute: () => rootRoute,
} as any);

const IntegrationRoute = IntegrationImport.update({
	path: "/integration",
	getParentRoute: () => rootRoute,
} as any);

const GenerateRoute = GenerateImport.update({
	path: "/generate",
	getParentRoute: () => rootRoute,
} as any);

const FaqsRoute = FaqsImport.update({
	path: "/faqs",
	getParentRoute: () => rootRoute,
} as any);

const ContactRoute = ContactImport.update({
	path: "/contact",
	getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
	path: "/auth",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/auth": {
			preLoaderRoute: typeof AuthImport;
			parentRoute: typeof rootRoute;
		};
		"/contact": {
			preLoaderRoute: typeof ContactImport;
			parentRoute: typeof rootRoute;
		};
		"/faqs": {
			preLoaderRoute: typeof FaqsImport;
			parentRoute: typeof rootRoute;
		};
		"/generate": {
			preLoaderRoute: typeof GenerateImport;
			parentRoute: typeof rootRoute;
		};
		"/integration": {
			preLoaderRoute: typeof IntegrationImport;
			parentRoute: typeof rootRoute;
		};
		"/pricing": {
			preLoaderRoute: typeof PricingImport;
			parentRoute: typeof rootRoute;
		};
		"/shorten": {
			preLoaderRoute: typeof ShortenImport;
			parentRoute: typeof rootRoute;
		};
		"/about": {
			preLoaderRoute: typeof AboutLazyImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
	IndexRoute,
	AuthRoute,
	ContactRoute,
	FaqsRoute,
	GenerateRoute,
	IntegrationRoute,
	PricingRoute,
	ShortenRoute,
	AboutLazyRoute,
]);

/* prettier-ignore-end */
