import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import { UIProvider } from "../contexts/ui-provider";
import "./globals.css";
import { NavHeader } from "@/components/nav-header";
import { PageFooter } from "@/components/page-footer";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-spacegrotesk",
});

export const metadata: Metadata = {
  title: "QR Code Generation and URL Shortening",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body
        className={`${spaceGrotesk.variable} font-sans font-normal bg-bg text-main min-h-screen`}
      >
        <UIProvider>
          <NavHeader />
          {children}
          <PageFooter />
        </UIProvider>
      </body>
    </html>
  );
}
