import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UIProvider } from "../contexts/ui-provider";
import "./globals.css";
import { NavHeader } from "@/components/navigation/nav-header";
import { PageFooter } from "@/components/page-footer";
import { cn } from "@/lib/utils";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "QR Code Generation and URL Shortening",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className='light'>
			<body
				className={cn(
					`font-inter min-h-screen bg-background antialiased`,
					inter.variable,
				)}>
				<UIProvider>
					<NavHeader />
					{children}
					<PageFooter />
				</UIProvider>
			</body>
		</html>
	);
}
