import { NextApiRequest } from "next";
import Head from "next/head";
import connectMongo from "../libraries/mongodb";

export async function getServerSideProps(request: NextApiRequest) {
  const hash = request.query.redirect as string;
  const database = await connectMongo();
  const campaign = await database.collection("url").findOne({ hash: hash });

  if (campaign?.link) {
    return {
      redirect: {
        permanent: false,
        destination: campaign?.link,
      },
    };
  }

  return {
    props: {},
  };
}

export default function Redirect() {
  return (
    <>
      <div>
        <Head>
          <title>URL Shortener</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 style={{ textAlign: "center" }}>Requested link not found</h1>
      </div>
    </>
  );
}
