import ArticleWrapper from "../components/ArticleWrapper";
import BlogCard from "../components/BlogCard";
import FaqWrapper from "../components/FaqWrapper";
import Footer from "../components/Footer";
import Head from "next/head";
import LandingTitle from "../components/LandingTitle";
import LandingSubTitle from "../components/LandingSubTitle";
import LandiingCaption from "../components/LandiingCaption";
import Navigation from "../components/Navigation";
import Wrapper from "../components/Wrapper";
import styled from "styled-components";
import { BiChevronRight } from "react-icons/bi";
import { BigButton } from "../components/Buttons";
import MeProfile from "../components/MeProfile";
import Heading from "../components/Heading";
import { faqHome } from "../libraries/data.js";
import React from "react";
import fs from "fs";
import path from "path";
import matter from "gray-matter";

export async function getStaticProps() {
  /* Get markdown files from mdx directory */
  const files = fs.readdirSync(path.join("mdx"));
  /* Return filenames as slugs */
  const articles = files.map((filename) => {
    const slug = filename.replace(".md", "");
    const mdxMeta = fs.readFileSync(path.join("mdx", filename), "utf-8");
    const { data: frontMatter } = matter(mdxMeta);

    return {
      slug,
      frontMatter,
    };
  });

  return {
    props: {
      articles: articles,
    },
  };
}

export default function Home({ articles }: { articles: any }) {
  let noteWrapper = React.useRef<HTMLDivElement>(null);
  let showcase = React.useRef<HTMLDivElement>(null);
  let showcaseSubtitle = React.useRef<HTMLHeadElement>(null);
  let showcaseTitle = React.useRef<HTMLHeadElement>(null);
  let showcaseCaption = React.useRef<HTMLParagraphElement>(null);
  let showcaseButons = React.useRef<HTMLDivElement>(null);

  return (
    <>
      <Head>
        <title>
          Barlink - Free URL shortener | Barcode and QR code generator
        </title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Navigation />
      <>
        {/* showcase */}
        <Showcase ref={showcase}>
          <Wrapper>
            <LandingSubTitle ref={showcaseSubtitle}>
              Your all-in-one Generator
            </LandingSubTitle>
            <LandingTitle ref={showcaseTitle}>
              Generate <span>Dynamic QR codes</span>, <span>Barcodes</span> and{" "}
              <span>Shorten Links</span>.
            </LandingTitle>
            <LandiingCaption ref={showcaseCaption}>
              Create fully customizable QR codes with your brand colors and
              logo, product barcodes. Turn long boring iinks to short momizable
              links. Download generated contents in several printable formats
              and high-quality.
            </LandiingCaption>

            <ShowcaseButtons ref={showcaseButons}>
              <BigButton primary={true}>
                Get started <BiChevronRight size={25} />
              </BigButton>
              <BigButton primary={false}>Scan QR-code</BigButton>
            </ShowcaseButtons>
          </Wrapper>
        </Showcase>
        {/* caption */}
        <CaptionSection>
          <Wrapper>
            <CaptionText>
              Your all-in-one platform to build interactive experience with your
              audience. Generate QR codes for sharing and embeding into your
              websites. Printable Barcodes for your products labeling. Provides
              your customers with unique links and tailored experience.
            </CaptionText>
          </Wrapper>
        </CaptionSection>
        {/* product detail */}
        <NoteSection>
          <Wrapper ref={noteWrapper}>
            <Note>
              <Heading>Full Customisable QR Code</Heading>
              <p>
                Add editable QR Codes on anything you want with full branding
                and customization feature
              </p>
              <p>
                A QR code is a two dimensional barcode that stores information
                in black and white dots (called data pixels or “QR code
                modules”). Besides the black and white version, you can also
                create a colored QR code. To make your QR code even better, you
                can also get a QR code with a logo.
              </p>
            </Note>
            <Note>
              <Heading>Short URLs - Simple & Fast</Heading>
              <p>
                Barlink transforms long, ugly looking links from top sites on
                the internet into nice, memorable, short URLs. just paste the
                long URL and with the click of a button, your short URL is
                generated.
              </p>
              <p>
                Your shortened URLs can be used in publications, documents,
                advertisements, blogs, forums, instant messages, and other
                locations.
              </p>
            </Note>
          </Wrapper>
        </NoteSection>
        {/* blog section */}
        <ArticleWrapper>
          {articles.map((post: any, idx: any) => (
            <BlogCard key={idx} article={post} />
          ))}
        </ArticleWrapper>
        {/* FAQs */}
        <FaqWrapper data={faqHome} />
        {/* profile */}
        <MeProfile />
      </>
      <Footer />
    </>
  );
}

const Showcase = styled.section`
  > * {
    min-height: var(--landing-height);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;

    p {
      margin: 1em 0;
    }
  }
`;

const ShowcaseButtons = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 1.25em;

  @media (max-width: 640px) {
    flex-direction: column;
    align-items: stretch;
    width: 100%;
    max-width: 300px;
  }
`;

const CaptionSection = styled.section`
  background-color: var(--clr-light);
  color: var(--clr-dark);
  padding: 0.5em 0;
`;

const CaptionText = styled.p`
  max-width: 740px;
  font-weight: var(--fw-smbold);
  font-size: 1.875rem;
  line-height: 141.5%;
  text-align: center;
  margin: 1.8em auto;

  @media (max-width: 768px) {
    font-size: 1.125rem;
  }
`;

const NoteSection = styled.section`
  > * {
    padding-block: 2em;
    display: flex;
    flex-direction: row;
    align-items: flex-start;
    justify-content: space-around;
    gap: 1.25rem;
    flex-wrap: wrap;
    background-color: var(--clr-white);
    color: var(--clr-dark);
  }
`;

const Note = styled.div`
  flex: 1;
  min-width: 300px;
  max-width: 593px;
`;
